// src/pages/simulation/components/editor/LandmarksPanel.jsx
//
// S.7.5+ — переработанный UI: карточки, статус-пилюля, segmented контрол
// для edit-режима, скроллируемый список групп с цветовыми индикаторами.

import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { useTranslation } from "react-i18next";
import {
  toggleLandmarkGroup,
  resetLandmarkEdits,
  selectLandmarks,
  selectLandmarksStatus,
  selectLandmarksDetectedAt,
  selectVisibleLandmarkGroups,
} from "../../store/simulationSlice.js";
import styles from "./LandmarksPanel.module.css";

const GROUPS = [
  { key: "face_oval", color: "#94a3b8" },
  { key: "forehead", color: "#fbbf24" },
  { key: "nose", color: "#3d7fff" },
  { key: "lips", color: "#ef4444" },
  { key: "left_eye", color: "#22c55e" },
  { key: "right_eye", color: "#22c55e" },
  { key: "left_eyebrow", color: "#f59e0b" },
  { key: "right_eyebrow", color: "#f59e0b" },
  { key: "left_cheek", color: "#ec4899" },
  { key: "right_cheek", color: "#ec4899" },
  { key: "left_jaw", color: "#06b6d4" },
  { key: "right_jaw", color: "#06b6d4" },
  { key: "chin", color: "#8b5cf6" },
  { key: "ears", color: "#14b8a6" },
  { key: "manual", color: "#a855f7" },
  { key: "other", color: "rgba(148, 163, 184, 0.7)" },
];

export default function LandmarksPanel({
  onReDetect,
  isLoaderReady,
  landmarkEditMode,
  onChangeEditMode,
}) {
  const { t } = useTranslation("Simulation");
  const dispatch = useDispatch();

  const landmarks = useSelector(selectLandmarks);
  const status = useSelector(selectLandmarksStatus);
  const detectedAt = useSelector(selectLandmarksDetectedAt);
  const visibleGroups = useSelector(selectVisibleLandmarkGroups);

  const visibleSet = new Set(visibleGroups);
  const isDetecting = status === "detecting";
  const canRedetect = isLoaderReady && !isDetecting;

  const totalCount = landmarks.length;
  const hiddenCount = landmarks.filter((lm) => lm.hidden).length;
  const manualCount = landmarks.filter(
    (lm) => lm.autoGenerated === false,
  ).length;
  const visibleCount = totalCount - hiddenCount;
  const hasLandmarks = totalCount > 0;
  const hasEdits = hiddenCount > 0 || manualCount > 0;

  const setEditMode = (mode) => {
    if (!onChangeEditMode) return;
    onChangeEditMode(landmarkEditMode === mode ? null : mode);
  };

  const handleReset = () => {
    if (window.confirm(t("landmarks.confirmReset"))) {
      dispatch(resetLandmarkEdits());
    }
  };

  return (
    <div className={styles.panel}>
      {/* ───── Header card ───── */}
      <div className={styles.headerCard}>
        <div className={styles.headerTop}>
          <h4 className={styles.title}>{t("landmarks.title")}</h4>
          <span
            className={`${styles.statusPill} ${styles[`status_${status}`]}`}
            aria-live="polite"
          >
            <span className={styles.statusDot} />
            {t(`landmarks.status.${status}`)}
          </span>
        </div>

        {hasLandmarks && (
          <div className={styles.statsRow}>
            <div className={styles.stat}>
              <span className={styles.statValue}>{visibleCount}</span>
              <span className={styles.statLabel}>
                {t("landmarks.statsVisible")}
              </span>
            </div>
            {hiddenCount > 0 && (
              <div className={styles.stat}>
                <span className={`${styles.statValue} ${styles.statMuted}`}>
                  {hiddenCount}
                </span>
                <span className={styles.statLabel}>
                  {t("landmarks.statsHidden")}
                </span>
              </div>
            )}
            {manualCount > 0 && (
              <div className={styles.stat}>
                <span className={`${styles.statValue} ${styles.statManual}`}>
                  {manualCount}
                </span>
                <span className={styles.statLabel}>
                  {t("landmarks.statsManual")}
                </span>
              </div>
            )}
          </div>
        )}

        {detectedAt && (
          <div className={styles.subtleInfo}>
            {t("landmarks.detectedAt", {
              time: new Date(detectedAt).toLocaleTimeString(),
            })}
          </div>
        )}
        {!isLoaderReady && (
          <div className={styles.subtleInfo}>
            {t("landmarks.loaderLoading")}
          </div>
        )}

        <button
          type="button"
          className={styles.primaryBtn}
          onClick={onReDetect}
          disabled={!canRedetect}
        >
          {isDetecting ? t("landmarks.detecting") : t("landmarks.redetect")}
        </button>
      </div>

      {/* ───── Edit toolbar card ───── */}
      {hasLandmarks && (
        <div className={styles.editCard}>
          <div className={styles.cardLabel}>{t("landmarks.editTools")}</div>

          <div className={styles.segmented}>
            <button
              type="button"
              className={`${styles.segBtn} ${
                landmarkEditMode === "addManual" ? styles.segBtnActive : ""
              }`}
              onClick={() => setEditMode("addManual")}
              title={t("landmarks.tools.addManualHint")}
            >
              <span className={styles.segIcon} aria-hidden>
                +
              </span>
              <span>{t("landmarks.tools.addManual")}</span>
            </button>
            <button
              type="button"
              className={`${styles.segBtn} ${
                landmarkEditMode === "hide" ? styles.segBtnActive : ""
              }`}
              onClick={() => setEditMode("hide")}
              title={t("landmarks.tools.hideHint")}
            >
              <span className={styles.segIcon} aria-hidden>
                −
              </span>
              <span>{t("landmarks.tools.hide")}</span>
            </button>
          </div>

          {landmarkEditMode === "addManual" && (
            <div className={styles.modeHint}>
              {t("landmarks.tools.addManualHint")}
            </div>
          )}
          {landmarkEditMode === "hide" && (
            <div className={styles.modeHint}>
              {t("landmarks.tools.hideHint")}
            </div>
          )}

          {hasEdits && (
            <button
              type="button"
              className={styles.resetBtn}
              onClick={handleReset}
              title={t("landmarks.resetHint")}
            >
              ↺ {t("landmarks.reset")}
            </button>
          )}
        </div>
      )}

      {/* ───── Workflow hint ───── */}
      {hasLandmarks && (
        <div className={styles.workflowHint}>{t("landmarks.workflowHint")}</div>
      )}

      {/* ───── Groups card ───── */}
      <div className={styles.groupsCard}>
        <div className={styles.cardLabel}>{t("landmarks.groups.title")}</div>
        <div className={styles.groupsScroll}>
          {GROUPS.map((g) => (
            <label key={g.key} className={styles.group}>
              <input
                type="checkbox"
                checked={visibleSet.has(g.key)}
                onChange={() => dispatch(toggleLandmarkGroup(g.key))}
              />
              <span
                className={styles.groupDot}
                style={{ background: g.color }}
                aria-hidden="true"
              />
              <span className={styles.groupName}>
                {t(`landmarks.groups.${g.key}`)}
              </span>
            </label>
          ))}
        </div>
      </div>
    </div>
  );
}
