// Единый источник истины для групп операций и их ключей.
// Сами переводы названий — в locales/{lang}/Surgery.json
//   procedures.{procedureKey}      → название процедуры
//   procedureGroups.{groupKey}     → название группы

export const PROCEDURE_GROUPS = [
  {
    groupKey: "facial_plastic",
    items: [
      "rhinoplasty",
      "blepharoplasty",
      "facelift",
      "brow_lift",
      "otoplasty",
      "chin_implant",
      "cheek_implant",
      "lip_augmentation",
      "lip_lift",
      "neck_lift",
      "fat_grafting_face",
      "ear_reconstruction",
    ],
  },
  {
    groupKey: "body_plastic",
    items: [
      "breast_augmentation",
      "breast_reduction",
      "breast_lift",
      "breast_reconstruction",
      "abdominoplasty",
      "liposuction",
      "bbl",
      "body_contouring",
      "arm_lift",
      "thigh_lift",
      "lower_body_lift",
      "gynecomastia",
      "labiaplasty",
      "vaginoplasty",
    ],
  },
  {
    groupKey: "abdominal",
    items: [
      "appendectomy",
      "cholecystectomy",
      "hernia_repair",
      "gastrectomy",
      "colectomy",
      "splenectomy",
      "bowel_resection",
      "liver_resection",
      "pancreatic_surgery",
      "rectal_surgery",
      "stoma_formation",
      "bariatric_sleeve",
      "bariatric_bypass",
      "bariatric_band",
    ],
  },
  {
    groupKey: "cardiac",
    items: [
      "cabg",
      "valve_replacement",
      "valve_repair",
      "aortic_surgery",
      "pacemaker",
      "icd_implant",
      "heart_transplant",
      "atrial_repair",
      "vad_implant",
      "pericardectomy",
    ],
  },
  {
    groupKey: "vascular",
    items: [
      "aaa_repair",
      "carotid_endarterectomy",
      "bypass_peripheral",
      "varicose_veins",
      "av_fistula",
      "embolectomy",
      "angioplasty",
      "amputation",
    ],
  },
  {
    groupKey: "neuro",
    items: [
      "craniotomy",
      "brain_tumor",
      "spine_discectomy",
      "spine_fusion",
      "laminectomy",
      "vp_shunt",
      "dbs",
      "aneurysm_clipping",
      "carpal_tunnel",
      "peripheral_nerve",
    ],
  },
  {
    groupKey: "thoracic",
    items: [
      "lobectomy",
      "pneumonectomy",
      "wedge_resection",
      "thymectomy",
      "esophagectomy",
      "pleurectomy",
      "lung_transplant",
      "chest_wall_repair",
    ],
  },
  {
    groupKey: "orthopedic",
    items: [
      "hip_replacement",
      "knee_replacement",
      "shoulder_replacement",
      "acl_repair",
      "meniscus_repair",
      "fracture_fixation",
      "arthroscopy",
      "spinal_deformity",
      "bone_tumor",
      "tendon_repair",
      "foot_surgery",
      "hand_surgery",
    ],
  },
  {
    groupKey: "urology",
    items: [
      "prostatectomy",
      "nephrectomy",
      "kidney_transplant",
      "ureteroscopy",
      "pcnl",
      "bladder_surgery",
      "cystectomy",
      "orchiectomy",
      "varicocele",
      "circumcision",
      "penile_implant",
      "sling_procedure",
    ],
  },
  {
    groupKey: "gynecology",
    items: [
      "hysterectomy",
      "myomectomy",
      "ovarian_cyst",
      "oophorectomy",
      "laparoscopy_gyn",
      "endometriosis",
      "tubal_ligation",
      "cesarean",
      "prolapse_repair",
      "cervical_conization",
    ],
  },
  {
    groupKey: "ophthalmology",
    items: [
      "cataract",
      "lasik",
      "glaucoma_surgery",
      "retinal_detachment",
      "vitrectomy",
      "strabismus",
      "corneal_transplant",
      "pterygium",
    ],
  },
  {
    groupKey: "ent",
    items: [
      "tonsillectomy",
      "adenoidectomy",
      "septoplasty",
      "sinus_surgery",
      "tympanoplasty",
      "cochlear_implant",
      "laryngoscopy",
      "parotidectomy",
      "thyroidectomy",
      "parathyroidectomy",
    ],
  },
  {
    groupKey: "oncology",
    items: [
      "mastectomy",
      "sentinel_node",
      "lymphadenectomy",
      "tumor_excision",
      "cytoreductive",
      "hipec",
      "exenteration",
      "port_implant",
    ],
  },
  {
    groupKey: "transplant",
    items: [
      "liver_transplant",
      "pancreas_transplant",
      "bone_marrow_transplant",
      "cornea_transplant",
      "hand_transplant",
      "face_transplant",
    ],
  },
  {
    groupKey: "pediatric",
    items: [
      "pyloric_stenosis",
      "intussusception",
      "hirschsprung",
      "cleft_lip_palate",
      "hypospadias",
      "undescended_testis",
      "vsd_asd_repair",
    ],
  },
  {
    groupKey: "other_group",
    items: [
      "dialysis_access",
      "wound_debridement",
      "abscess_drainage",
      "circumcision_adult",
      "pilonidal_cyst",
      "hemorrhoidectomy",
      "fistula_repair",
      "skin_graft",
      "other",
    ],
  },
];

// Плоский список всех ключей процедур — для случаев, где нужны просто все коды
export const ALL_PROCEDURE_KEYS = PROCEDURE_GROUPS.flatMap((g) => g.items);
