export const countryPhoneMeta = {
  AF: { name: "Afghanistan", code: "+93", digits: 9 },
  AL: { name: "Albania", code: "+355", digits: 9 },
  DZ: { name: "Algeria", code: "+213", digits: 9 },
  AD: { name: "Andorra", code: "+376", digits: 6 },
  AO: { name: "Angola", code: "+244", digits: 9 },
  AR: { name: "Argentina", code: "+54", digits: 10 },
  AM: { name: "Armenia", code: "+374", digits: 8 },
  AU: { name: "Australia", code: "+61", digits: 9 },
  AT: { name: "Austria", code: "+43", digits: 10 },
  AZ: { name: "Azerbaijan", code: "+994", digits: 9 },
  BH: { name: "Bahrain", code: "+973", digits: 8 },
  BD: { name: "Bangladesh", code: "+880", digits: 10 },
  BY: { name: "Belarus", code: "+375", digits: 9 },
  BE: { name: "Belgium", code: "+32", digits: 9 },
  BR: { name: "Brazil", code: "+55", digits: 10 },
  BG: { name: "Bulgaria", code: "+359", digits: 9 },
  CA: { name: "Canada", code: "+1", digits: 10 },
  CN: { name: "China", code: "+86", digits: 11 },
  HR: { name: "Croatia", code: "+385", digits: 9 },
  CY: { name: "Cyprus", code: "+357", digits: 8 },
  CZ: { name: "Czech Republic", code: "+420", digits: 9 },
  DK: { name: "Denmark", code: "+45", digits: 8 },
  EG: { name: "Egypt", code: "+20", digits: 10 },
  EE: { name: "Estonia", code: "+372", digits: 8 },
  FI: { name: "Finland", code: "+358", digits: 9 },
  FR: { name: "France", code: "+33", digits: 9 },
  GE: { name: "Georgia", code: "+995", digits: 9 },
  DE: { name: "Germany", code: "+49", digits: 10 },
  GR: { name: "Greece", code: "+30", digits: 10 },
  HU: { name: "Hungary", code: "+36", digits: 9 },
  IS: { name: "Iceland", code: "+354", digits: 7 },
  IN: { name: "India", code: "+91", digits: 10 },
  IR: { name: "Iran", code: "+98", digits: 10 },
  IQ: { name: "Iraq", code: "+964", digits: 10 },
  IE: { name: "Ireland", code: "+353", digits: 9 },
  IL: { name: "Israel", code: "+972", digits: 9 },
  IT: { name: "Italy", code: "+39", digits: 10 },
  JP: { name: "Japan", code: "+81", digits: 10 },
  JO: { name: "Jordan", code: "+962", digits: 9 },
  KZ: { name: "Kazakhstan", code: "+7", digits: 10 },
  KW: { name: "Kuwait", code: "+965", digits: 8 },
  KG: { name: "Kyrgyzstan", code: "+996", digits: 9 },
  LV: { name: "Latvia", code: "+371", digits: 8 },
  LB: { name: "Lebanon", code: "+961", digits: 8 },
  LT: { name: "Lithuania", code: "+370", digits: 8 },
  LU: { name: "Luxembourg", code: "+352", digits: 9 },
  MY: { name: "Malaysia", code: "+60", digits: 9 },
  MX: { name: "Mexico", code: "+52", digits: 10 },
  MD: { name: "Moldova", code: "+373", digits: 8 },
  MC: { name: "Monaco", code: "+377", digits: 8 },
  MN: { name: "Mongolia", code: "+976", digits: 8 },
  ME: { name: "Montenegro", code: "+382", digits: 8 },
  MA: { name: "Morocco", code: "+212", digits: 9 },
  NL: { name: "Netherlands", code: "+31", digits: 9 },
  NZ: { name: "New Zealand", code: "+64", digits: 9 },
  NG: { name: "Nigeria", code: "+234", digits: 10 },
  MK: { name: "North Macedonia", code: "+389", digits: 8 },
  NO: { name: "Norway", code: "+47", digits: 8 },
  OM: { name: "Oman", code: "+968", digits: 8 },
  PK: { name: "Pakistan", code: "+92", digits: 10 },
  PS: { name: "Palestine", code: "+970", digits: 9 },
  PE: { name: "Peru", code: "+51", digits: 9 },
  PH: { name: "Philippines", code: "+63", digits: 10 },
  PL: { name: "Poland", code: "+48", digits: 9 },
  PT: { name: "Portugal", code: "+351", digits: 9 },
  QA: { name: "Qatar", code: "+974", digits: 8 },
  RO: { name: "Romania", code: "+40", digits: 9 },
  RU: { name: "Russia", code: "+7", digits: 10 },
  SA: { name: "Saudi Arabia", code: "+966", digits: 9 },
  RS: { name: "Serbia", code: "+381", digits: 8 },
  SG: { name: "Singapore", code: "+65", digits: 8 },
  SK: { name: "Slovakia", code: "+421", digits: 9 },
  SI: { name: "Slovenia", code: "+386", digits: 8 },
  ZA: { name: "South Africa", code: "+27", digits: 9 },
  KR: { name: "South Korea", code: "+82", digits: 9 },
  ES: { name: "Spain", code: "+34", digits: 9 },
  LK: { name: "Sri Lanka", code: "+94", digits: 9 },
  SE: { name: "Sweden", code: "+46", digits: 9 },
  CH: { name: "Switzerland", code: "+41", digits: 9 },
  SY: { name: "Syria", code: "+963", digits: 9 },
  TW: { name: "Taiwan", code: "+886", digits: 9 },
  TJ: { name: "Tajikistan", code: "+992", digits: 9 },
  TZ: { name: "Tanzania", code: "+255", digits: 9 },
  TH: { name: "Thailand", code: "+66", digits: 9 },
  TR: { name: "Turkey", code: "+90", digits: 10 },
  TM: { name: "Turkmenistan", code: "+993", digits: 8 },
  AE: { name: "United Arab Emirates", code: "+971", digits: 9 },
  UG: { name: "Uganda", code: "+256", digits: 9 },
  UA: { name: "Ukraine", code: "+380", digits: 9 },
  GB: { name: "United Kingdom", code: "+44", digits: 10 },
  US: { name: "United States", code: "+1", digits: 10 },
  UY: { name: "Uruguay", code: "+598", digits: 9 },
  UZ: { name: "Uzbekistan", code: "+998", digits: 9 },
  VN: { name: "Vietnam", code: "+84", digits: 9 },
  YE: { name: "Yemen", code: "+967", digits: 9 },
  ZM: { name: "Zambia", code: "+260", digits: 9 },
  ZW: { name: "Zimbabwe", code: "+263", digits: 9 },
};
