// client/src/pages/simulation/hooks/useFaceDetection.js
//
// Хук для автоматической детекции анатомических точек лица.
// Использует MediaPipe FaceLandmarker (468 точек).
//
// Usage:
//   const { isReady, isLoading, error, runDetection } = useFaceDetection();
//   const { landmarks, detected } = await runDetection(imageBitmap);

import { useCallback, useEffect, useRef, useState } from "react";
import { loadFaceLandmarker } from "../mediapipe/faceLandmarkerLoader";
import { getLandmarkGroup } from "../mediapipe/faceLandmarksGroups";

/**
 * @typedef {Object} DetectedLandmark
 * @property {string}  id               - стабильный id (lm_<index>)
 * @property {number}  mediapipeIndex   - 0..467, индекс в canonical face mesh
 * @property {string}  group            - nose | lips | left_eye | ... | other
 * @property {number}  x                - normalized [0..1]
 * @property {number}  y                - normalized [0..1]
 * @property {number}  z                - depth, normalized (знак: от камеры)
 * @property {boolean} autoGenerated    - true (всегда, для отличия от ручных)
 */

/**
 * @typedef {Object} DetectionResult
 * @property {DetectedLandmark[]} landmarks  - 468 точек или []
 * @property {boolean}            detected   - true если лицо найдено
 */

export function useFaceDetection() {
  const [isLoading, setIsLoading] = useState(true);
  const [isReady, setIsReady] = useState(false);
  const [error, setError] = useState(null);

  const landmarkerRef = useRef(null);
  const isMountedRef = useRef(true);

  useEffect(() => {
    isMountedRef.current = true;

    loadFaceLandmarker()
      .then((landmarker) => {
        if (!isMountedRef.current) return;
        landmarkerRef.current = landmarker;
        setIsReady(true);
        setIsLoading(false);
      })
      .catch((err) => {
        if (!isMountedRef.current) return;
        // eslint-disable-next-line no-console
        console.error("[useFaceDetection] Failed to load FaceLandmarker:", err);
        setError(err);
        setIsLoading(false);
      });

    return () => {
      isMountedRef.current = false;
    };
  }, []);

  /**
   * Запускает детекцию по изображению.
   * Принимает ImageBitmap, HTMLImageElement, HTMLCanvasElement, HTMLVideoElement, ImageData.
   *
   * @param {ImageBitmap|HTMLImageElement|HTMLCanvasElement|HTMLVideoElement|ImageData} imageSource
   * @returns {Promise<DetectionResult>}
   */
  const runDetection = useCallback(async (imageSource) => {
    if (!landmarkerRef.current) {
      throw new Error("Face Landmarker is not ready yet");
    }
    if (!imageSource) {
      throw new Error("imageSource is required");
    }

    // В режиме IMAGE detect() синхронный.
    const result = landmarkerRef.current.detect(imageSource);

    const faces = result?.faceLandmarks || [];
    if (faces.length === 0) {
      return { landmarks: [], detected: false };
    }

    // Берём первое лицо (numFaces: 1 в конфиге).
    const face = faces[0]; // Array<{x, y, z}>, длина 468

    const landmarks = face.map((point, index) => ({
      id: `lm_${index}`,
      mediapipeIndex: index,
      group: getLandmarkGroup(index),
      x: point.x, // уже normalized [0..1]
      y: point.y,
      z: point.z, // depth, отн. единицы
      autoGenerated: true,
    }));

    return { landmarks, detected: true };
  }, []);

  return { isLoading, isReady, error, runDetection };
}
