// client/src/pages/simulation/hooks/useFaceDetection.js
//
// Хук для автоматической детекции анатомических точек лица.
// Использует MediaPipe FaceLandmarker (478 точек, включая iris).
//
// S.7.7+: при обнаружении нескольких лиц возвращает ВСЕ детектированные
// лица (не выбирает одно молча).
//
// S.7.7+ (B): rotation retry — если 0 лиц на оригинале, пробуем повернуть
// изображение на 90/180/270° и продетектировать там. Если на повёрнутом
// фото нашлось лицо — возвращаем landmarks с обратной трансформацией
// координат, чтобы они легли на оригинальное фото правильно.
//
// Это помогает в случаях когда:
//   • Фото загружено с неправильной EXIF-ориентацией
//   • Клиент отдал rotated thumbnail
//   • Фото снято с телефона в landscape но на самом деле portrait
//
// На extreme close-up profile (где видна половина головы) rotation НЕ
// поможет — это поведение модели, не баг ориентации.

import { useCallback, useEffect, useRef, useState } from "react";
import { loadFaceLandmarker } from "../mediapipe/faceLandmarkerLoader";
import { getLandmarkGroup } from "../mediapipe/faceLandmarksGroups";

/**
 * @typedef {Object} DetectedLandmark
 * @property {string}  id
 * @property {number}  mediapipeIndex
 * @property {string}  group
 * @property {number}  x                - normalized [0..1]
 * @property {number}  y                - normalized [0..1]
 * @property {number}  z
 * @property {boolean} autoGenerated
 */

/**
 * @typedef {Object} FaceVariant
 * @property {DetectedLandmark[]} landmarks
 * @property {Object}             bbox
 */

/**
 * @typedef {Object} DetectionResult
 * @property {DetectedLandmark[]} landmarks
 * @property {FaceVariant[]}      faces
 * @property {number}             selectedIndex
 * @property {boolean}            detected
 * @property {number}             [rotationUsed]  - 0|90|180|270, если сработал retry
 */

const ROTATION_RETRIES = [90, 180, 270]; // в градусах CW

/**
 * Считает bounding box лица в normalized coordinates.
 */
function faceBoundingBox(faceLandmarks) {
  let minX = 1;
  let minY = 1;
  let maxX = 0;
  let maxY = 0;
  for (let i = 0; i < faceLandmarks.length; i++) {
    const p = faceLandmarks[i];
    if (p.x < minX) minX = p.x;
    if (p.y < minY) minY = p.y;
    if (p.x > maxX) maxX = p.x;
    if (p.y > maxY) maxY = p.y;
  }
  return {
    minX,
    minY,
    maxX,
    maxY,
    centerX: (minX + maxX) / 2,
    centerY: (minY + maxY) / 2,
    area: (maxX - minX) * (maxY - minY),
  };
}

/**
 * Маппит сырые MediaPipe landmarks в наш формат.
 */
function mapLandmarks(faceLandmarks) {
  return faceLandmarks.map((point, index) => ({
    id: `lm_${index}`,
    mediapipeIndex: index,
    group: getLandmarkGroup(index),
    x: point.x,
    y: point.y,
    z: point.z,
    autoGenerated: true,
  }));
}

/**
 * Создаёт canvas с повёрнутым изображением.
 * Поворот — CW (по часовой) на degrees градусов.
 *
 * @param {HTMLImageElement|ImageBitmap|HTMLCanvasElement} imageSource
 * @param {number} degrees - 90 | 180 | 270
 * @returns {HTMLCanvasElement}
 */
function rotateImageToCanvas(imageSource, degrees) {
  const w = imageSource.width || imageSource.naturalWidth;
  const h = imageSource.height || imageSource.naturalHeight;

  const canvas = document.createElement("canvas");
  // Для 90 и 270 градусов канвас "поворачивается" — width и height меняются
  if (degrees === 90 || degrees === 270) {
    canvas.width = h;
    canvas.height = w;
  } else {
    canvas.width = w;
    canvas.height = h;
  }

  const ctx = canvas.getContext("2d");
  ctx.save();
  // Перевод origin в центр канваса, поворот, рисуем картинку центрированно
  ctx.translate(canvas.width / 2, canvas.height / 2);
  ctx.rotate((degrees * Math.PI) / 180);
  ctx.drawImage(imageSource, -w / 2, -h / 2);
  ctx.restore();
  return canvas;
}

/**
 * Обратное преобразование normalized координат с повёрнутого изображения
 * в координаты оригинала.
 *
 * Если изображение было повёрнуто на degrees CW, то для возврата в
 * оригинал точку (x', y') на повёрнутом нужно повернуть на -degrees CW
 * (= degrees CCW).
 *
 * Все координаты — normalized [0..1].
 *
 * @param {number} x  - normalized x на повёрнутом изображении
 * @param {number} y  - normalized y на повёрнутом изображении
 * @param {number} degrees - на сколько было повёрнуто (90|180|270)
 * @returns {{x: number, y: number}} - normalized на оригинале
 */
function unrotateNormalized(x, y, degrees) {
  // На повёрнутом изображении (x, y) ∈ [0, 1].
  // В системе оригинала ширина/высота были другими, но в normalized системе
  // [0,1] это не важно — мы просто применяем обратный поворот.
  switch (degrees) {
    case 90:
      // CW 90 повернул точку (x0, y0) → (1 - y0, x0). Обратно: (y, 1 - x).
      return { x: y, y: 1 - x };
    case 180:
      return { x: 1 - x, y: 1 - y };
    case 270:
      // CW 270 повернул (x0, y0) → (y0, 1 - x0). Обратно: (1 - y, x).
      return { x: 1 - y, y: x };
    default:
      return { x, y };
  }
}

/**
 * Применяет обратное преобразование ко всему массиву landmarks.
 */
function unrotateLandmarks(landmarks, degrees) {
  if (degrees === 0) return landmarks;
  return landmarks.map((lm) => {
    const { x, y } = unrotateNormalized(lm.x, lm.y, degrees);
    return { ...lm, x, y };
  });
}

export function useFaceDetection() {
  const [isLoading, setIsLoading] = useState(true);
  const [isReady, setIsReady] = useState(false);
  const [error, setError] = useState(null);

  const landmarkerRef = useRef(null);
  const isMountedRef = useRef(true);

  useEffect(() => {
    isMountedRef.current = true;

    loadFaceLandmarker()
      .then((landmarker) => {
        if (!isMountedRef.current) return;
        landmarkerRef.current = landmarker;
        setIsReady(true);
        setIsLoading(false);
      })
      .catch((err) => {
        if (!isMountedRef.current) return;
        // eslint-disable-next-line no-console
        console.error("[useFaceDetection] Failed to load FaceLandmarker:", err);
        setError(err);
        setIsLoading(false);
      });

    return () => {
      isMountedRef.current = false;
    };
  }, []);

  /**
   * Внутренний detect — без rotation retry.
   * Возвращает массив сырых faces или [].
   */
  const detectOnce = useCallback((imageSource) => {
    if (!landmarkerRef.current) {
      throw new Error("Face Landmarker is not ready yet");
    }
    const result = landmarkerRef.current.detect(imageSource);
    return result?.faceLandmarks || [];
  }, []);

  /**
   * Запускает детекцию по изображению с rotation retry.
   *
   * @param {ImageBitmap|HTMLImageElement|HTMLCanvasElement} imageSource
   * @returns {Promise<DetectionResult>}
   */
  const runDetection = useCallback(
    async (imageSource) => {
      if (!landmarkerRef.current) {
        throw new Error("Face Landmarker is not ready yet");
      }
      if (!imageSource) {
        throw new Error("imageSource is required");
      }

      let facesRaw = detectOnce(imageSource);
      let rotationUsed = 0;

      // Rotation retry — только если на оригинале не нашлось ни одного лица
      if (facesRaw.length === 0) {
        // eslint-disable-next-line no-console
        console.info(
          "[useFaceDetection] 0 faces on original, trying rotations 90/180/270…",
        );

        for (const deg of ROTATION_RETRIES) {
          try {
            const rotatedCanvas = rotateImageToCanvas(imageSource, deg);
            const rotatedFaces = detectOnce(rotatedCanvas);
            if (rotatedFaces.length > 0) {
              // eslint-disable-next-line no-console
              console.info(
                `[useFaceDetection] Found ${rotatedFaces.length} face(s) after rotating ${deg}°`,
              );
              facesRaw = rotatedFaces;
              rotationUsed = deg;
              break;
            }
          } catch (err) {
            // eslint-disable-next-line no-console
            console.warn(
              `[useFaceDetection] Rotation ${deg}° failed:`,
              err?.message || err,
            );
          }
        }
      }

      if (facesRaw.length === 0) {
        // eslint-disable-next-line no-console
        console.warn(
          "[useFaceDetection] No face detected after all rotation retries. Image may be too small, blurry, in extreme close-up, or partially occluded.",
        );
        return {
          landmarks: [],
          faces: [],
          selectedIndex: -1,
          detected: false,
          rotationUsed: 0,
        };
      }

      // Если нашли через rotation — преобразуем координаты обратно
      const faces = facesRaw.map((raw) => {
        const mapped = mapLandmarks(raw);
        const corrected =
          rotationUsed > 0 ? unrotateLandmarks(mapped, rotationUsed) : mapped;
        // bbox считаем на скорректированных координатах — чтобы он был
        // в системе оригинала
        return {
          landmarks: corrected,
          bbox: faceBoundingBox(corrected),
        };
      });

      // Выбираем по умолчанию лицо с наибольшим bbox
      let selectedIndex = 0;
      let maxArea = faces[0].bbox.area;
      for (let i = 1; i < faces.length; i++) {
        if (faces[i].bbox.area > maxArea) {
          maxArea = faces[i].bbox.area;
          selectedIndex = i;
        }
      }

      if (faces.length > 1) {
        // eslint-disable-next-line no-console
        console.info(
          `[useFaceDetection] ${faces.length} faces detected, default=${selectedIndex} (largest area)`,
        );
      }

      return {
        landmarks: faces[selectedIndex].landmarks,
        faces,
        selectedIndex,
        detected: true,
        rotationUsed,
      };
    },
    [detectOnce],
  );

  return { isLoading, isReady, error, runDetection };
}
