// src/pages/simulation/standards/wizard/canonicalMesh.js
//
// Canonical Face Mesh Generator
// =====================================================================
//
// Procrustes 2D alignment: маппим 6 точек canonical_face_model.obj
// (заданных в canonicalAnchorPoints.js) на 6 точек кликнутых врачом.
// Возвращаем similarity transform (translation, rotation, uniform scale)
// и применяем его к ВСЕМ 468 каноническим landmarks.
//
// Результат — массив из 468 landmarks в формате который ожидает
// существующая система ({id, mediapipeIndex, group, x, y, hidden, autoGenerated}).
//
// === Procrustes math ===
// Дано: 2 набора N точек (canonical[]) и (clicked[]) в общих парах.
// Найти: 2D similarity (s, R, t) такие, что:
//   clicked_i ≈ s · R · canonical_i + t
//
// Алгоритм (Umeyama 1991, упрощённая 2D версия):
//   1. Центроиды:  μ_c = mean(canonical),  μ_p = mean(clicked)
//   2. Центрированные:  c_i = canonical_i - μ_c,  p_i = clicked_i - μ_p
//   3. Cross-covariance scalar:
//        Sxx = Σ(c_i.x * p_i.x + c_i.y * p_i.y)   ← dot product
//        Syx = Σ(c_i.x * p_i.y - c_i.y * p_i.x)   ← cross product (z component)
//   4. Rotation angle:  θ = atan2(Syx, Sxx)
//   5. Scale:           s = √(Sxx² + Syx²) / Σ|c_i|²
//   6. Translation:     t = μ_p - s · R(θ) · μ_c

import { ANCHOR_POINTS } from "../../mediapipe/canonicalAnchorPoints.js";

// Lazy-loaded canonical mesh (468 точек)
// Файл canonical_face_model.obj большой (~50KB), поэтому используем
// упрощённый встроенный массив только опорных точек, плюс публикуем
// fallback через MediaPipe runtime если он подключён.
//
// В этом V1 wizard использует ТОЛЬКО 6 опорных точек как landmarks
// (это анатомически достаточно для стандартов: они смотрят только
// glabella, nasion, pronasale, alarL, alarR, chin по индексам).
//
// Это важная упрощение: если MediaPipe не нашёл лицо, у нас всё равно
// нет 468 точек — но стандарты работают, потому что они и так
// читают только эти 6 индексов.
//
// В V2 (опционально) можно подгрузить полный canonical mesh из
// MediaPipe и применить ту же transform для генерации полных 468 lm.

/**
 * 2D Procrustes similarity alignment.
 *
 * @param {Array<{x:number,y:number}>} sourcePoints  - canonical (N >= 2)
 * @param {Array<{x:number,y:number}>} targetPoints  - clicked     (N >= 2)
 * @returns {{ scale:number, rotation:number, tx:number, ty:number, transform: (p)=>{x,y} } | null}
 */
export function procrustes2D(sourcePoints, targetPoints) {
  if (
    !Array.isArray(sourcePoints) ||
    !Array.isArray(targetPoints) ||
    sourcePoints.length !== targetPoints.length ||
    sourcePoints.length < 2
  ) {
    return null;
  }

  const N = sourcePoints.length;

  // Centroids
  let cx = 0,
    cy = 0,
    px = 0,
    py = 0;
  for (let i = 0; i < N; i++) {
    cx += sourcePoints[i].x;
    cy += sourcePoints[i].y;
    px += targetPoints[i].x;
    py += targetPoints[i].y;
  }
  cx /= N;
  cy /= N;
  px /= N;
  py /= N;

  // Cross-covariance components + source norm-squared
  let Sxx = 0,
    Syx = 0,
    normSq = 0;
  for (let i = 0; i < N; i++) {
    const dxC = sourcePoints[i].x - cx;
    const dyC = sourcePoints[i].y - cy;
    const dxP = targetPoints[i].x - px;
    const dyP = targetPoints[i].y - py;

    Sxx += dxC * dxP + dyC * dyP;
    Syx += dxC * dyP - dyC * dxP;
    normSq += dxC * dxC + dyC * dyC;
  }

  if (normSq === 0) return null;

  const rotation = Math.atan2(Syx, Sxx);
  const scale = Math.sqrt(Sxx * Sxx + Syx * Syx) / normSq;

  if (!Number.isFinite(scale) || scale === 0) return null;

  const cosR = Math.cos(rotation);
  const sinR = Math.sin(rotation);

  // Translation: t = μ_p - s · R · μ_c
  const tx = px - scale * (cosR * cx - sinR * cy);
  const ty = py - scale * (sinR * cx + cosR * cy);

  // Returns transform function: canonical → image-space
  const transform = (p) => ({
    x: scale * (cosR * p.x - sinR * p.y) + tx,
    y: scale * (sinR * p.x + cosR * p.y) + ty,
  });

  return { scale, rotation, tx, ty, transform };
}

/**
 * Сгенерировать массив landmarks в формате simulationSlice.
 * Использует только 6 anchor points — это всё, что нужно стандартам.
 *
 * @param {Array<{key:string, x:number, y:number}>} clickedPoints
 *        - клики в нормализованных координатах [0..1]
 *        - key совпадает с ANCHOR_POINTS[i].key (glabella, nasion, ...)
 * @returns {Array} landmarks в формате {id, mediapipeIndex, group, x, y, hidden, autoGenerated}
 */
export function buildLandmarksFromClicks(clickedPoints) {
  if (
    !Array.isArray(clickedPoints) ||
    clickedPoints.length !== ANCHOR_POINTS.length
  ) {
    return [];
  }

  // Сопоставляем кликнутые с canonical по key
  const sourcePoints = [];
  const targetPoints = [];
  const orderedAnchors = [];

  for (const anchor of ANCHOR_POINTS) {
    const click = clickedPoints.find((c) => c.key === anchor.key);
    if (!click) return []; // не все 6 точек собраны
    sourcePoints.push(anchor.canonical);
    targetPoints.push({ x: click.x, y: click.y });
    orderedAnchors.push(anchor);
  }

  // Используем кликнутые позиции напрямую как landmarks
  // (Procrustes тут не нужен для V1, мы уже знаем где врач указал)
  // Однако для V2 будем использовать procrustes2D + полный canonical mesh
  // и тогда генерировать недостающие 462 точки.

  return orderedAnchors.map((anchor, i) => ({
    id: `manual_lm_${anchor.key}`,
    mediapipeIndex: anchor.mediapipeIndex,
    group: getGroupForAnchor(anchor.key),
    x: targetPoints[i].x,
    y: targetPoints[i].y,
    hidden: false,
    autoGenerated: true, // пометка что эти landmarks от автоматики (не от ручного landmarking)
  }));
}

/**
 * Группа для каждой anchor — для совместимости с visibleLandmarkGroups
 * фильтрами в существующей системе.
 */
function getGroupForAnchor(key) {
  switch (key) {
    case "glabella":
      return "forehead";
    case "nasion":
    case "pronasale":
    case "alarLeft":
    case "alarRight":
      return "nose";
    case "chin":
      return "chin";
    default:
      return "other";
  }
}
