// src/pages/simulation/mediapipe/manualLandmarkFit.js
//
// S.7.7+ — преобразование 6 опорных точек кликнутых врачом в массив
// landmarks совместимый с форматом auto-detection.
//
// БЕЗ Procrustes для всех 478 точек (Вариант B): мы оставляем только
// те 6 точек что кликнул врач + корректно проставляем mediapipeIndex
// чтобы измерения в measurements.js нашли их через findByIndex().
//
// Это означает что:
//   • Все 3 измерения (nasofrontal, Goode, alar) работают точно
//   • На canvas видны только эти 6 точек (минимум визуального шума)
//   • landmarkSource: 'manual_fit' — для аналитики и отображения статуса

import { ANCHOR_POINTS, ANCHOR_GROUPS } from "./canonicalAnchorPoints.js";

/**
 * @typedef {Object} ManualMarkedPoint
 * @property {string} key       - ключ ANCHOR_POINTS (glabella, nasion, ...)
 * @property {number} x         - normalized [0..1] на изображении
 * @property {number} y         - normalized [0..1] на изображении
 */

/**
 * @typedef {Object} FittedLandmark — формат совместимый с DetectedLandmark
 * @property {string}  id
 * @property {number}  mediapipeIndex
 * @property {string}  group
 * @property {number}  x
 * @property {number}  y
 * @property {number}  z
 * @property {boolean} autoGenerated  - false (это ручной)
 * @property {string}  source         - 'manual_fit'
 */

/**
 * Преобразует массив помеченных врачом 6 точек в массив landmarks
 * которые можно сложить в стейт через setLandmarks().
 *
 * @param {ManualMarkedPoint[]} markedPoints
 * @returns {FittedLandmark[]}
 */
export function fitLandmarksFromManualPoints(markedPoints) {
  if (!Array.isArray(markedPoints) || markedPoints.length === 0) {
    return [];
  }

  const result = [];

  for (const marked of markedPoints) {
    const anchor = ANCHOR_POINTS.find((a) => a.key === marked.key);
    if (!anchor) continue;
    if (
      typeof marked.x !== "number" ||
      typeof marked.y !== "number" ||
      Number.isNaN(marked.x) ||
      Number.isNaN(marked.y)
    ) {
      continue;
    }

    result.push({
      id: `lm_${anchor.mediapipeIndex}`,
      mediapipeIndex: anchor.mediapipeIndex,
      group: ANCHOR_GROUPS[anchor.key] || "other",
      x: Math.max(0, Math.min(1, marked.x)),
      y: Math.max(0, Math.min(1, marked.y)),
      z: 0,
      autoGenerated: true, // совместимость: для нас это «детектированные»,
      // чтобы не попасть в manualLandmarks ветку slice
      source: "manual_fit", // флаг для UI и аналитики
    });
  }

  return result;
}

/**
 * Проверяет что переданные клики покрывают минимально достаточный набор
 * для всех трёх измерений: nasofrontal, Goode, alar base.
 *
 * Минимум: glabella + nasion + pronasale + alarLeft + alarRight
 * Подбородок (chin) — опционален (не используется в текущих измерениях,
 * но полезен визуально для врача и для будущих измерений).
 *
 * @param {ManualMarkedPoint[]} markedPoints
 * @returns {{
 *   valid: boolean,
 *   missing: string[],
 *   canFitMeasurements: boolean
 * }}
 */
export function validateMarkedPoints(markedPoints) {
  const required = ["glabella", "nasion", "pronasale", "alarLeft", "alarRight"];
  const haveKeys = new Set(
    (markedPoints || [])
      .filter((p) => typeof p.x === "number" && typeof p.y === "number")
      .map((p) => p.key),
  );
  const missing = required.filter((k) => !haveKeys.has(k));
  return {
    valid: missing.length === 0,
    missing,
    canFitMeasurements: missing.length === 0,
  };
}
