// src/pages/simulation/store/simulationSlice.js
import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import * as api from "../api/simulationApi.js";
import { uploadPhoto as apiUploadPhoto } from "../api/photoUploadApi.js";

/* ──────────────────────────────────────────────────────────────────────────
   S.7.3: persistLandmarks для сохранения landmarks на сервере.
   S.7.4: visibleMeasurements для UI-видимости измерений.
   S.7.5: расширение модели landmark — поля `hidden` и `autoGenerated`.
          Новые reducers:
            - toggleLandmarkHidden(id)
            - addManualLandmark({ x, y, group? })
            - removeLandmark(id)        // только для manual; для авто = hidden=true
            - resetLandmarkEdits()      // снять все hidden, удалить все manual
          Новая группа landmark'ов: 'manual' (фиолетовая).
   ────────────────────────────────────────────────────────────────────────── */

const DEFAULT_VISIBLE_GROUPS = [
  "face_oval",
  "forehead",
  "nose",
  "lips",
  "left_eye",
  "right_eye",
  "left_eyebrow",
  "right_eyebrow",
  "left_cheek",
  "right_cheek",
  "left_jaw",
  "right_jaw",
  "chin",
  "manual",
  "other",
];

const DEFAULT_VISIBLE_MEASUREMENTS = {
  nasofrontalAngle: true,
  goodeProjection: true,
  alarBaseWidth: true,
};

const initialState = {
  list: [],
  listCursor: null,
  listHasMore: false,
  current: null,
  loading: {
    list: false,
    current: false,
    create: false,
    update: false,
    delete: false,
    upload: false,
    persistLandmarks: false,
  },
  error: null,
  uploadProgress: 0,
  visibleLandmarkGroups: DEFAULT_VISIBLE_GROUPS,
  visibleMeasurements: DEFAULT_VISIBLE_MEASUREMENTS,
};

/* ──────────────────────────────────────────────────────────────────────
   normalizePlan: гарантирует что у каждого landmark есть поля hidden и
   autoGenerated. Старые записи в БД могут не иметь этих полей.
   ────────────────────────────────────────────────────────────────────── */
function normalizePlan(plan) {
  if (!plan) return plan;
  const rawLandmarks = Array.isArray(plan.landmarks) ? plan.landmarks : [];
  const landmarks = rawLandmarks.map((lm) => ({
    ...lm,
    hidden: Boolean(lm.hidden),
    autoGenerated: lm.autoGenerated !== false, // по умолчанию true
  }));
  const meta = plan.landmarksMeta || {};
  return {
    ...plan,
    landmarks,
    landmarksDetectedAt: meta.detectedAt || null,
    landmarksStatus: landmarks.length > 0 ? "detected" : "idle",
  };
}

/* ─────── ID generators ─────── */
let manualLandmarkCounter = 0;
function genManualLandmarkId() {
  manualLandmarkCounter += 1;
  return `manual_${Date.now().toString(36)}_${manualLandmarkCounter}`;
}

/* ─────── Thunks ─────── */

export const fetchPlans = createAsyncThunk(
  "simulation/fetchPlans",
  async ({ reset = true } = {}, { getState, rejectWithValue }) => {
    try {
      const state = getState().simulation;
      const cursor = reset ? null : state.listCursor;
      const result = await api.listPlans({ limit: 30, cursor });
      return { ...result, reset };
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);

export const fetchPlanById = createAsyncThunk(
  "simulation/fetchPlanById",
  async (id, { rejectWithValue }) => {
    try {
      return await api.getPlan(id);
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);

export const uploadPhoto = createAsyncThunk(
  "simulation/uploadPhoto",
  async (file, { dispatch, rejectWithValue }) => {
    try {
      return await apiUploadPhoto(file, {
        onProgress: (pct) => dispatch(setUploadProgress(pct)),
      });
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);

export const createPlan = createAsyncThunk(
  "simulation/createPlan",
  async (payload, { rejectWithValue }) => {
    try {
      return await api.createPlan(payload);
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);

export const updatePlan = createAsyncThunk(
  "simulation/updatePlan",
  async ({ id, patch }, { rejectWithValue }) => {
    try {
      return await api.updatePlan(id, patch);
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);

export const deletePlan = createAsyncThunk(
  "simulation/deletePlan",
  async (id, { rejectWithValue }) => {
    try {
      await api.deletePlan(id);
      return id;
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);

export const duplicatePlan = createAsyncThunk(
  "simulation/duplicatePlan",
  async ({ id, label }, { rejectWithValue }) => {
    try {
      return await api.duplicatePlan(id, { label });
    } catch (err) {
      return rejectWithValue(err);
    }
  },
);

/* ─────── persistLandmarks ─────── */
export const persistLandmarks = createAsyncThunk(
  "simulation/persistLandmarks",
  async ({ id, landmarks, meta }, { rejectWithValue }) => {
    try {
      return await api.saveLandmarks(id, landmarks, meta);
    } catch (err) {
      return rejectWithValue(err?.response?.data || err);
    }
  },
);

/* ─────── Slice ─────── */

const slice = createSlice({
  name: "simulation",
  initialState,
  reducers: {
    clearError(state) {
      state.error = null;
    },
    clearCurrent(state) {
      state.current = null;
    },
    setUploadProgress(state, action) {
      state.uploadProgress = action.payload;
    },
    resetUpload(state) {
      state.uploadProgress = 0;
    },
    setCurrentControlPoints(state, action) {
      if (state.current) {
        state.current.controlPoints = action.payload;
      }
    },

    /* S.7 — landmarks (локальные) */
    setLandmarks(state, action) {
      if (!state.current) return;
      const incoming = action.payload || [];

      // S.7.5: при re-detect сохраняем флаги hidden для совпадающих
      // mediapipeIndex'ов, чтобы пользовательские правки не сбрасывались.
      // Manual landmarks полностью сохраняем — детекция их не трогает.
      const previous = state.current.landmarks || [];
      const hiddenByIndex = new Map();
      const manualPoints = [];

      for (const lm of previous) {
        if (lm.autoGenerated === false) {
          manualPoints.push(lm);
        } else if (lm.hidden && typeof lm.mediapipeIndex === "number") {
          hiddenByIndex.set(lm.mediapipeIndex, true);
        }
      }

      const merged = incoming.map((lm) => ({
        ...lm,
        hidden: hiddenByIndex.has(lm.mediapipeIndex)
          ? true
          : Boolean(lm.hidden),
        autoGenerated: true,
      }));

      // Manual landmarks добавляем после авто-точек
      state.current.landmarks = [...merged, ...manualPoints];
      state.current.landmarksDetectedAt = new Date().toISOString();
      state.current.landmarksStatus = "detected";
    },
    clearLandmarks(state) {
      if (!state.current) return;
      state.current.landmarks = [];
      state.current.landmarksDetectedAt = null;
      state.current.landmarksStatus = "idle";
    },
    setLandmarksStatus(state, action) {
      if (!state.current) return;
      state.current.landmarksStatus = action.payload;
    },
    toggleLandmarkGroup(state, action) {
      const group = action.payload;
      const idx = state.visibleLandmarkGroups.indexOf(group);
      if (idx === -1) state.visibleLandmarkGroups.push(group);
      else state.visibleLandmarkGroups.splice(idx, 1);
    },
    setVisibleLandmarkGroups(state, action) {
      state.visibleLandmarkGroups = action.payload;
    },

    /* S.7.5 — manual edits */
    /**
     * Скрыть/показать landmark по id. Для авто-точек используется
     * флаг hidden (точка остаётся в массиве, но не отображается).
     */
    toggleLandmarkHidden(state, action) {
      if (!state.current?.landmarks) return;
      const id = action.payload;
      const lm = state.current.landmarks.find((l) => l.id === id);
      if (lm) lm.hidden = !lm.hidden;
    },

    /**
     * Удалить landmark.
     *   - Если manual (autoGenerated=false) → удаляется из массива
     *   - Если auto → ставится hidden=true (можно вернуть через reset)
     */
    removeLandmark(state, action) {
      if (!state.current?.landmarks) return;
      const id = action.payload;
      const lm = state.current.landmarks.find((l) => l.id === id);
      if (!lm) return;

      if (lm.autoGenerated === false) {
        state.current.landmarks = state.current.landmarks.filter(
          (l) => l.id !== id,
        );
      } else {
        lm.hidden = true;
      }
    },

    /**
     * Добавить ручной landmark в координатах (x, y).
     * x, y — нормализованные [0..1].
     */
    addManualLandmark(state, action) {
      if (!state.current) return;
      if (!Array.isArray(state.current.landmarks)) {
        state.current.landmarks = [];
      }
      const { x, y, group = "manual" } = action.payload || {};
      if (typeof x !== "number" || typeof y !== "number") return;

      const newLm = {
        id: genManualLandmarkId(),
        mediapipeIndex: -1,
        group,
        x: Math.max(0, Math.min(1, x)),
        y: Math.max(0, Math.min(1, y)),
        hidden: false,
        autoGenerated: false,
      };
      state.current.landmarks.push(newLm);
    },

    /**
     * Сбросить все правки: показать все скрытые auto-точки и удалить
     * все ручные. Используется кнопкой "Сбросить" в LandmarksPanel.
     */
    resetLandmarkEdits(state) {
      if (!state.current?.landmarks) return;
      state.current.landmarks = state.current.landmarks
        .filter((lm) => lm.autoGenerated !== false)
        .map((lm) => ({ ...lm, hidden: false }));
    },

    /* S.7.4 — measurements visibility */
    toggleMeasurement(state, action) {
      const key = action.payload;
      if (key in state.visibleMeasurements) {
        state.visibleMeasurements[key] = !state.visibleMeasurements[key];
      }
    },
    setVisibleMeasurements(state, action) {
      state.visibleMeasurements = {
        ...state.visibleMeasurements,
        ...action.payload,
      };
    },
  },
  extraReducers: (builder) => {
    builder.addCase(fetchPlans.pending, (state) => {
      state.loading.list = true;
      state.error = null;
    });
    builder.addCase(fetchPlans.fulfilled, (state, { payload }) => {
      state.loading.list = false;
      state.list = payload.reset
        ? payload.items
        : [...state.list, ...payload.items];
      state.listCursor = payload.nextCursor;
      state.listHasMore = payload.hasMore;
    });
    builder.addCase(fetchPlans.rejected, (state, { payload }) => {
      state.loading.list = false;
      state.error = payload;
    });

    builder.addCase(fetchPlanById.pending, (state) => {
      state.loading.current = true;
      state.error = null;
    });
    builder.addCase(fetchPlanById.fulfilled, (state, { payload }) => {
      state.loading.current = false;
      state.current = normalizePlan(payload);
    });
    builder.addCase(fetchPlanById.rejected, (state, { payload }) => {
      state.loading.current = false;
      state.error = payload;
    });

    builder.addCase(uploadPhoto.pending, (state) => {
      state.loading.upload = true;
      state.error = null;
      state.uploadProgress = 0;
    });
    builder.addCase(uploadPhoto.fulfilled, (state) => {
      state.loading.upload = false;
      state.uploadProgress = 100;
    });
    builder.addCase(uploadPhoto.rejected, (state, { payload }) => {
      state.loading.upload = false;
      state.uploadProgress = 0;
      state.error = payload;
    });

    builder.addCase(createPlan.pending, (state) => {
      state.loading.create = true;
      state.error = null;
    });
    builder.addCase(createPlan.fulfilled, (state, { payload }) => {
      state.loading.create = false;
      state.list = [payload, ...state.list];
    });
    builder.addCase(createPlan.rejected, (state, { payload }) => {
      state.loading.create = false;
      state.error = payload;
    });

    builder.addCase(updatePlan.pending, (state) => {
      state.loading.update = true;
      state.error = null;
    });
    builder.addCase(updatePlan.fulfilled, (state, { payload }) => {
      state.loading.update = false;
      state.list = state.list.map((p) => (p.id === payload.id ? payload : p));
      if (state.current?.id === payload.id) {
        state.current = normalizePlan(payload);
      }
    });
    builder.addCase(updatePlan.rejected, (state, { payload }) => {
      state.loading.update = false;
      state.error = payload;
    });

    builder.addCase(deletePlan.pending, (state) => {
      state.loading.delete = true;
      state.error = null;
    });
    builder.addCase(deletePlan.fulfilled, (state, { payload: id }) => {
      state.loading.delete = false;
      state.list = state.list.filter((p) => p.id !== id);
      if (state.current?.id === id) state.current = null;
    });
    builder.addCase(deletePlan.rejected, (state, { payload }) => {
      state.loading.delete = false;
      state.error = payload;
    });

    builder.addCase(duplicatePlan.fulfilled, (state, { payload }) => {
      state.list = [payload, ...state.list];
    });
    builder.addCase(duplicatePlan.rejected, (state, { payload }) => {
      state.error = payload;
    });

    builder.addCase(persistLandmarks.pending, (state) => {
      state.loading.persistLandmarks = true;
      state.error = null;
    });
    builder.addCase(persistLandmarks.fulfilled, (state, { payload }) => {
      state.loading.persistLandmarks = false;
      if (state.current?.id === payload.id) {
        state.current = normalizePlan(payload);
      }
    });
    builder.addCase(persistLandmarks.rejected, (state, { payload }) => {
      state.loading.persistLandmarks = false;
      // eslint-disable-next-line no-console
      console.error("[simulationSlice] persistLandmarks failed:", payload);
    });
  },
});

export const {
  clearError,
  clearCurrent,
  setUploadProgress,
  resetUpload,
  setCurrentControlPoints,
  setLandmarks,
  clearLandmarks,
  setLandmarksStatus,
  toggleLandmarkGroup,
  setVisibleLandmarkGroups,
  toggleLandmarkHidden,
  removeLandmark,
  addManualLandmark,
  resetLandmarkEdits,
  toggleMeasurement,
  setVisibleMeasurements,
} = slice.actions;

export default slice.reducer;

/* ─────── Selectors ─────── */

export const selectPlans = (s) => s.simulation.list;
export const selectPlansCursor = (s) => s.simulation.listCursor;
export const selectHasMore = (s) => s.simulation.listHasMore;
export const selectCurrentPlan = (s) => s.simulation.current;
export const selectLoading = (s) => s.simulation.loading;
export const selectError = (s) => s.simulation.error;
export const selectUploadProgress = (s) => s.simulation.uploadProgress;

/**
 * selectLandmarks возвращает ВСЕ landmarks (включая hidden). Фильтрация
 * по hidden происходит в Overlay/Panel — потому что Panel должен
 * показывать счётчики (всего/скрыто) и иметь доступ к hidden точкам.
 */
export const selectLandmarks = (s) => s.simulation.current?.landmarks || [];

/**
 * selectVisibleLandmarks — только не-hidden (для рендера на canvas).
 */
export const selectVisibleLandmarks = (s) => {
  const all = s.simulation.current?.landmarks || [];
  return all.filter((lm) => !lm.hidden);
};

export const selectLandmarksStatus = (s) =>
  s.simulation.current?.landmarksStatus || "idle";
export const selectLandmarksDetectedAt = (s) =>
  s.simulation.current?.landmarksDetectedAt || null;
export const selectVisibleLandmarkGroups = (s) =>
  s.simulation.visibleLandmarkGroups;
export const selectIsPersistingLandmarks = (s) =>
  s.simulation.loading.persistLandmarks;

export const selectVisibleMeasurements = (s) =>
  s.simulation.visibleMeasurements;
